version: 2
updates:
  # Root package.json / package-lock.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "development"
    open-pull-requests-limit: 10

  # apps/api/package.json
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
    target-branch: "development"
    open-pull-requests-limit: 10
